# robotpkg youBot
#

COMMENT=	youBot

SUBDIR+=	youbot-manipulation
SUBDIR+=	youbot-stack-utwente
SUBDIR+=	youbot-ros-pkg
SUBDIR+=	youbot_applications
SUBDIR+=	b-it-bots_youbot-ros-pkg



include ../mk/robotpkg.subdir.mk
