# generated on 2012-07-01

PACKAGE_VERSION = 1
DISTNAME = artoolkitplusstack-${PACKAGE_VERSION}
PKGNAME = artoolkitplusstack-${PACKAGE_VERSION}
CATEGORIES = algorithm
MASTER_SITES = http://brics.inf.h-brs.de/
MASTER_REPOSITORY = 

MAINTAINER = Maintained by Roalter Luis
HOMEPAGE = http://ros.org/wiki/artoolkitplus
COMMENT = artoolkitplus
LICENSE = modified-bsd

NO_CONFIGURE = yes
NO_BUILD = yes
NO_EXTRACT = yes

do-install:
	${RUN} tar -C $(ROBOTPKG_BASE) -xvf ${DISTDIR}/${DISTNAME}${EXTRACT_SUFX}

include ../../mk/robotpkg.mk
